{"uuid": "89dd491c-e59d-4b89-a12d-9346e2f16438", "children": ["4198e280-4d64-4f08-800c-e9d454e92817", "ada2c8d1-7770-4a08-902a-519d826215a1"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1737288505157, "stop": 1737288505157}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Vishal\\PycharmProjects\\pytestautomationdemo\\Pages\\LoginPage.py\", line 31, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1737288525477, "stop": 1737288525480}], "start": 1737288505157, "stop": 1737288525480}